server:
  port: 9003
spring:
  h2:
    console:
      enabled=true:
  datasource:
    url=jdbc:h2:mem:product:
  application:
    name: PRODUCT-SERVICE
  profiles:
    active: dev
  boot:
    admin:
      client:
        url:
          - http://localhost:9009
product:
  currencies:
    - USD
    - ZWL
    - SAR
logging:
  file:
    name: product.log
  logback:
    rollingpolicy:
      max-file-size: 100KB
  #  path: d:\ogs
#actauto specific endpoints
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always

---
server:
  port: 9006
spring:
  config:
    activate:
      on-profile:
        - dev