server:
  port: 9003
spring:
  h2:
    console:
      enabled=true:
  datasource:
    url=jdbc:h2:mem:product:
  application:
    name: PRODUCT-SERVICE
  profiles:
    active: dev
product:
  currencies:
    - USD
    - ZWL
    - SAR
logging:
  file:
    name: product.log
  #  path: d:\ogs
---
server:
  port: 9006
spring:
  config:
    activate:
      on-profile:
        - dev